name: Deploy to LAMP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Remove .git before deploy
        run: rm -rf .git

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ciss298.zenren.xyz
          username: deployuser
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: "/var/www/ciss298-TeamProject"
          strip_components: 1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ciss298.zenren.xyz
          username: deployuser
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/ciss298-TeamProject
            chmod -R 755 .
            echo "DB_HOST=localhost" > .env
            echo "DB_USER=root" >> .env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
            echo "DB_NAME=hotel" >> .env
            echo "WEATHER=${{ secrets.WEATHER }}" >> .env

